import { promises as fs } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { toLF } from '@s3xysteak/utils'
import { expGenerator } from '@/core/index'

describe.concurrent('generate', () => {
  /** TS */
  it('expGenerator should work with TS', async () => {
    const exportList = ['custom', 'two', 'getThree', 'funcIndex', 'ClassIndex', 'func3', 'func2', 'func1', 'fRe'].sort()

    const target = `
// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = ${JSON.stringify(exportList)} as const

/**
 * @returns Call in \`imports\` option of \`unplugin-auto-import\`.
 */
export default function autoImport(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>): Record<string, (string | [string, string])[]> {
  return {
    'unplugin-export-collector': __UnExportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
`

    await expGenerator('./test/parser-lab/index.ts', {
      include: ['custom'],
      exclude: ['one'],
      writeTo: './test/parser-lab/generatorTest.ts',
    })
    const result = await fs.readFile('./test/parser-lab/generatorTest.ts', 'utf-8')
    expect(toLF(result)).toBe(`${target.trim()}\n`)
  })

  /** JS */
  it('expGenerator should work with JS', async () => {
    const exportList = ['custom', 'two', 'getThree', 'funcIndex', 'ClassIndex', 'func3', 'func2', 'func1', 'fRe'].sort()

    const target = `
// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = /** @type {const} */ (${JSON.stringify(exportList)})

/**
 * @param {Partial<{ [K in typeof __UnExportList[number]]: string }>} [map]
 * @returns {Record<string, (string | [string, string])[]>} Call in \`imports\` option of \`unplugin-auto-import\`.
 */
export default function autoImport(map) {
  return {
    'unplugin-export-collector': __UnExportList.map(v => map && map[v] ? [v, map[v]] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
`

    await expGenerator('./test/parser-lab/index.js', {
      include: ['custom'],
      exclude: ['one'],
      typescript: false,
      writeTo: './test/parser-lab/generatorTest.js',
    })
    const result = await fs.readFile('./test/parser-lab/generatorTest.js', 'utf-8')
    expect(toLF(result)).toBe(`${target.trim()}\n`)
  })

  /** resolvers */
  it('should work with ts resolvers', async () => {
    const exportList = ['custom', 'two', 'getThree', 'funcIndex', 'ClassIndex', 'func3', 'func2', 'func1', 'fRe'].sort()

    const target = `
// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = ${JSON.stringify(exportList)} as const

/**
 * @returns Call in \`resolvers\` option of \`unplugin-auto-import\`.
 */
export default function autoImport(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>) {
  return (name: string) => {
    if (!__UnExportList.includes(name as any))
      return

    return map && (map as any)[name]
      ? {
          name,
          as: (map as any)[name],
          from: 'unplugin-export-collector',
        }
      : {
          name,
          from: 'unplugin-export-collector',
        }
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
`

    await expGenerator('./test/parser-lab/index.ts', {
      include: ['custom'],
      exclude: ['one'],
      type: 'resolvers',
      writeTo: './test/parser-lab/generatorTest-resolvers.ts',
    })

    const result = await fs.readFile('./test/parser-lab/generatorTest-resolvers.ts', 'utf-8')

    expect(toLF(result)).toBe(`${target.trim()}\n`)
  })

  it('should work with js resolvers', async () => {
    const exportList = ['custom', 'two', 'getThree', 'funcIndex', 'ClassIndex', 'func3', 'func2', 'func1', 'fRe'].sort()

    const target = `
// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = /** @type {const} */ (${JSON.stringify(exportList)})

/**
 * @param {Partial<{ [K in typeof __UnExportList[number]]: string }>} [map]
 * @returns Call in \`resolvers\` option of \`unplugin-auto-import\`.
 */
export default function autoImport(map) {
  /** @param {string} name */
  const func = (name) => {
    if (!__UnExportList.includes(name))
      return

    return map && map[name]
      ? {
          name,
          as: map[name],
          from: 'unplugin-export-collector',
        }
      : {
          name,
          from: 'unplugin-export-collector',
        }
  }
  return func
}

// --- Auto-Generated By Unplugin-Export-Collector ---
`

    await expGenerator('./test/parser-lab/index.js', {
      include: ['custom'],
      exclude: ['one'],
      typescript: false,
      type: 'resolvers',
      writeTo: './test/parser-lab/generatorTest-resolvers.js',
    })

    const result = await fs.readFile('./test/parser-lab/generatorTest-resolvers.js', 'utf-8')

    expect(toLF(result)).toBe(`${target.trim()}\n`)
  })

  /** aliases */
  it('expGenerator should work with aliases', async () => {
    const exportList = ['custom', 'two', 'getThree', 'funcIndex', 'ClassIndex', 'func3', 'func2', 'func1', 'fRe'].sort()

    const target = `
// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = ${JSON.stringify(exportList)} as const

/**
 * @returns Call in \`imports\` option of \`unplugin-auto-import\`.
 */
export default function autoImport(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>): Record<string, (string | [string, string])[]> {
  return {
    'unplugin-export-collector': __UnExportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
`

    await expGenerator('./test/parser-lab/index-alias.ts', {
      include: ['custom'],
      exclude: ['one'],
      alias: {
        '~test': fileURLToPath(new URL('.', import.meta.url)),
      },
      writeTo: './test/parser-lab/generatorTest-alias.ts',
    })

    const result = await fs.readFile('./test/parser-lab/generatorTest-alias.ts', 'utf-8')

    expect(toLF(result)).toBe(`${target.trim()}\n`)
  })
})
