/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Console: typeof import('../src/utils/general')['Console']
  const afterAll: typeof import('vitest')['afterAll']
  const afterEach: typeof import('vitest')['afterEach']
  const assert: typeof import('vitest')['assert']
  const beforeAll: typeof import('vitest')['beforeAll']
  const beforeEach: typeof import('vitest')['beforeEach']
  const chai: typeof import('vitest')['chai']
  const describe: typeof import('vitest')['describe']
  const expect: typeof import('vitest')['expect']
  const it: typeof import('vitest')['it']
  const onDev: typeof import('../src/utils/general')['onDev']
  const suite: typeof import('vitest')['suite']
  const test: typeof import('vitest')['test']
  const vi: typeof import('vitest')['vi']
  const vitest: typeof import('vitest')['vitest']
}
