/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Console: typeof import('../src/utils/general')['Console']
  const afterAll: typeof import('vitest')['afterAll']
  const afterEach: typeof import('vitest')['afterEach']
  const assert: typeof import('vitest')['assert']
  const beforeAll: typeof import('vitest')['beforeAll']
  const beforeEach: typeof import('vitest')['beforeEach']
  const chai: typeof import('vitest')['chai']
  const describe: typeof import('vitest')['describe']
  const expect: typeof import('vitest')['expect']
  const flow: typeof import('@s3xysteak/utils')['flow']
  const isArray: typeof import('@s3xysteak/utils')['isArray']
  const isBoolean: typeof import('@s3xysteak/utils')['isBoolean']
  const isDate: typeof import('@s3xysteak/utils')['isDate']
  const isDef: typeof import('@s3xysteak/utils')['isDef']
  const isFunction: typeof import('@s3xysteak/utils')['isFunction']
  const isInRange: typeof import('@s3xysteak/utils')['isInRange']
  const isNull: typeof import('@s3xysteak/utils')['isNull']
  const isNumber: typeof import('@s3xysteak/utils')['isNumber']
  const isObject: typeof import('@s3xysteak/utils')['isObject']
  const isRegExp: typeof import('@s3xysteak/utils')['isRegExp']
  const isString: typeof import('@s3xysteak/utils')['isString']
  const isUndefined: typeof import('@s3xysteak/utils')['isUndefined']
  const it: typeof import('vitest')['it']
  const onDev: typeof import('../src/utils/general')['onDev']
  const sleep: typeof import('@s3xysteak/utils')['sleep']
  const suite: typeof import('vitest')['suite']
  const test: typeof import('vitest')['test']
  const toNumber: typeof import('@s3xysteak/utils')['toNumber']
  const vi: typeof import('vitest')['vi']
  const vitest: typeof import('vitest')['vitest']
}
