import process from 'node:process'
import { promises as fs } from 'node:fs'
import { expCollector } from './parser'
import { findPath, getPkg } from './utils'

const comment = '// --- Auto-Generated By Unplugin-Export-Collector ---'
const firstIndex = (content: string) => content.indexOf(comment)
const lastIndex = (content: string) => content.lastIndexOf(comment) + comment.length

export interface ExpGeneratorOptions {
  base: string
  pkgName: string
  include: string[]
  exclude: string[]
  rename: string
}

export async function expGenerator(path: string, options?: Partial<ExpGeneratorOptions>) {
  const { data, targetPath } = await expGeneratorData(path, options)
  await fs.writeFile(targetPath, data)
}

export async function expGeneratorData(path: string, options?: Partial<ExpGeneratorOptions>) {
  const pkg = await getPkg()

  const {
    base = process.cwd(),
    pkgName = pkg.name,
    include = [],
    exclude = [],
    rename = 'autoImport',
  } = options ?? {}

  exclude.push(rename)

  const targetPath = await findPath(path, base)

  const expList = await expCollector(path, base)
  let content = await fs.readFile(targetPath, 'utf-8')

  const _firstComment = firstIndex(content)

  if (_firstComment === -1) {
    content = `${content}\n
${comment}
${comment}
`
  }

  const firstComment = firstIndex(content)
  const lastComment = lastIndex(content)

  const exportList = [...expList, ...include].filter(i => !exclude.includes(i)).sort()

  const val = `
${content.substring(0, firstComment).trim()}

${comment}

const __UnExportList = ${JSON.stringify(exportList)} as const

export function ${rename}(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>): Record<string, (string | [string, string])[]> {
  return {
    '${pkgName}': __UnExportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

${comment}

${content.substring(lastComment).trim()}
`

  return {
    data: `${val.trim()}\n`,
    targetPath,
  }
}
