export const COMMENT = '// --- Auto-Generated By Unplugin-Export-Collector ---'
const firstIndex = (content: string) => content.indexOf(COMMENT)
const lastIndex = (content: string) => content.lastIndexOf(COMMENT) + COMMENT.length

export function generateTemplate(content: string, body: string) {
  if (firstIndex(content) === -1) {
    content = `${content}\n
${COMMENT}
${COMMENT}
`
  }

  const firstComment = firstIndex(content)
  const lastComment = lastIndex(content)

  return `
${content.substring(0, firstComment).trim()}

${COMMENT}

${body.trim()}

${COMMENT}

${content.substring(lastComment).trim()}
`
}

// export function resolversImports(exportList: string[], pkgName: string, rename: string, exportDefault: boolean) {
//   return {
//     ts: ``,
//     js: ``,
//   }
// }

export function resolversTemplate(exportList: string[], pkgName: string, rename: string, exportDefault: boolean) {
  return {
    ts: `
const __UnExportList = ${JSON.stringify(exportList)} as const

/**
 * @returns Call in \`resolvers\` option of \`unplugin-auto-import\`.
 */
${exportDefault ? 'export default' : 'export'} function ${rename}(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>) {
  return (name: string) => {
    if (!__UnExportList.includes(name as any))
      return

    return map && (map as any)[name]
      ? {
          name,
          as: (map as any)[name],
          from: '${pkgName}',
        }
      : {
          name,
          from: '${pkgName}',
        }
  }
}
`,
    js: `
const __UnExportList = /** @type {const} */ (${JSON.stringify(exportList)})

/**
 * @param {Partial<{ [K in typeof __UnExportList[number]]: string }>} [map]
 * @returns Call in \`resolvers\` option of \`unplugin-auto-import\`.
 */
${exportDefault ? 'export default' : 'export'} function ${rename}(map) {
  /** @param {string} name */
  const func = (name) => {
    if (!__UnExportList.includes(name))
      return

    return map && map[name]
      ? {
          name,
          as: map[name],
          from: '${pkgName}',
        }
      : {
          name,
          from: '${pkgName}',
        }
  }
  return func
}
`,
  }
}
