export const one = 1
export const two = 2
export const getThree = () => 3
export function funcIndex() {}
export class ClassIndex {}

export type NumOrStr = number | string

export * from './core/func1'
export * from '~test/parser-lab/core/func2'

export * from '@s3xysteak/utils'

// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = ["ClassIndex","custom","fRe","func1","func2","func3","funcIndex","getThree","two"] as const

/**
 * @returns Call in `resolvers` option of `unplugin-auto-import`.
 */
export function autoImport(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>) {
  return (name: string) => {
    if (!__UnExportList.includes(name as any))
      return

    return map && (map as any)[name]
      ? {
          name,
          as: (map as any)[name],
          from: 'unplugin-export-collector',
        }
      : {
          name,
          from: 'unplugin-export-collector',
        }
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
