// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = /** @type {const} */ (["ClassIndex","custom","fRe","func1","func2","func3","funcIndex","getThree","two"])

/**
 * @param {Partial<{ [K in typeof __UnExportList[number]]: string }>} [map]
 * @returns {Record<string, (string | [string, string])[]>} Call in `imports` option of `unplugin-auto-import`.
 */
export default function autoImport(map) {
  return {
    '@unplugin-export-collector/monorepo': __UnExportList.map(v => map && map[v] ? [v, map[v]] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
