export * from './func1'

export function func3() {
  return 3
}

// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = ["func1","func3","funcRe","hi"] as const

export function autoImport(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>): Record<string, (string | [string, string])[]> {
  return {
    'lab-vite': __UnExportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
